# -*- coding: utf-8 -*-
"""Python_Code_For_Tensile_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1APsZDixAzIb93VcjTcGHQdnTwjfXHozs
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ===============================
# 🔹 UPLOAD FILE
# ===============================
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_excel(file_name)

print("Columns in file:", df.columns)

# ===============================
# 🔹 INPUT VALUES
# ===============================
A0 = 71.91e-6   # m²
L0 = 70e-3      # m
Af = 68.73e-6   # m²
Lf = 74e-3      # m

# ===============================
# 🔹 CLEAN COLUMN NAMES
# ===============================
df.columns = df.columns.str.strip()

# ===============================
# 🔹 DATA EXTRACTION
# ===============================
force = df['LOAD(N)'].values
strain = df['STRAIN(mm/mm)'].values

# Remove NaNs
mask = ~np.isnan(force) & ~np.isnan(strain)
force = force[mask]
strain = strain[mask]

# ===============================
# 🔹 STRESS
# ===============================
stress = force / A0
stress_MPa = stress / 1e6

# ===============================
# 🔹 TRUE STRESS-STRAIN
# ===============================
true_strain = np.log(1 + strain)
true_stress = stress * (1 + strain)
true_stress_MPa = true_stress / 1e6

# ===============================
# 🔹 ELASTIC REGION (EXTENSOMETER)
# ===============================
elastic_limit_index = 55

# ===============================
# 🔹 YOUNG’S MODULUS (EXTENSOMETER)
# ===============================
E_ext = np.polyfit(strain[:elastic_limit_index], stress[:elastic_limit_index], 1)[0]
E_ext_GPa = E_ext / 1e9

# ===============================
# 🔹 YOUNG’S MODULUS (ACTUATOR REGION)
# ===============================
# take small initial linear part after 56 (important)
act_start = 56
act_end = min(80, len(strain))   # take limited points to stay near linear

E_act = np.polyfit(strain[act_start:act_end], stress[act_start:act_end], 1)[0]
E_act_GPa = E_act / 1e9

# ===============================
# 🔹 LIMIT OF PROPORTIONALITY
# ===============================
LOP = stress_MPa[elastic_limit_index]

# ===============================
# 🔹 YIELD STRENGTH
# ===============================
offset = 0.002
offset_line = E_ext * (strain - offset)

YS = None
for i in range(len(stress)):
    if stress[i] >= offset_line[i]:
        YS = stress_MPa[i]
        break

# ===============================
# 🔹 UTS
# ===============================
UTS = np.max(stress_MPa)

# ===============================
# 🔹 ELONGATION & REDUCTION
# ===============================
percent_elongation = ((Lf - L0) / L0) * 100
percent_RA = ((A0 - Af) / A0) * 100

# ===============================
# 🔹 RESILIENCE (FIXED)
# ===============================
# sort only elastic region to avoid negative area
strain_el = strain[:elastic_limit_index]
stress_el = stress[:elastic_limit_index]

sorted_idx = np.argsort(strain_el)
strain_el = strain_el[sorted_idx]
stress_el = stress_el[sorted_idx]

resilience = np.trapz(stress_el, strain_el)

# ===============================
# 🔹 TOUGHNESS
# ===============================
toughness = np.trapz(stress, strain)

# ===============================
# 🔹 PLOTTING (UNCHANGED)
# ===============================
plt.figure(figsize=(6,5))
plt.plot(strain, stress_MPa)
plt.xlabel("Strain")
plt.ylabel("Stress (MPa)")
plt.title("Engineering Stress-Strain Curve")
plt.grid()
plt.show()

plt.figure(figsize=(6,5))
plt.plot(true_strain, true_stress_MPa)
plt.xlabel("True Strain")
plt.ylabel("True Stress (MPa)")
plt.title("True Stress-Strain Curve")
plt.grid()
plt.show()

# ===============================
# 🔹 RESULTS
# ===============================
print("\n===== FINAL RESULTS =====")
print(f"Young’s Modulus (Extensometer) = {E_ext_GPa:.2f} GPa")
print(f"Young’s Modulus (Actuator) = {E_act_GPa:.2f} GPa")
print(f"Limit of Proportionality (LOP) = {LOP:.2f} MPa")
print(f"Yield Strength (YS) = {YS:.2f} MPa")
print(f"Ultimate Tensile Strength (UTS) = {UTS:.2f} MPa")
print(f"% Elongation = {percent_elongation:.2f} %")
print(f"% Reduction in Area = {percent_RA:.2f} %")
print(f"Resilience = {resilience:.2f} J/m³")
print(f"Toughness = {toughness:.2f} J/m³")