# -*- coding: utf-8 -*-
"""Python_Code_For_Compression_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0RS6_g0UhgoRzkX5RDOCJ0RWkYVtGs4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -------------------------------
# FUNCTION: SCIENTIFIC FORMAT
# -------------------------------
def sci_notation(x):
    exponent = int(np.floor(np.log10(abs(x))))
    coeff = x / (10**exponent)
    return f"{coeff:.2f} × 10^{exponent}"

# -------------------------------
# LOAD DATA
# -------------------------------
from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]
data = pd.read_excel(filename)

# -------------------------------
# CLEAN COLUMN NAMES
# -------------------------------
data.columns = data.columns.str.strip()
print("Columns:", data.columns)

# -------------------------------
# EXTRACT RAW DATA
# -------------------------------
strain = data['STRAIN(mm/mm)'].values
stress = data['STRESS(Pa)'].values

# 👉 REQUIRED FOR ΔL and FORCE
force = data['LOAD(N)'].values
length = data['LENGTH(mm)'].values

# -------------------------------
# INITIAL LENGTH
# -------------------------------
L0 = length[0]

# -------------------------------
# SORT DATA (IMPORTANT)
# -------------------------------
sorted_indices = np.argsort(strain)

strain = strain[sorted_indices]
stress = stress[sorted_indices]
force = force[sorted_indices]
length = length[sorted_indices]

# -------------------------------
# 1. YOUNG'S MODULUS
# -------------------------------
n = 10
coeffs = np.polyfit(strain[:n], stress[:n], 1)
E = coeffs[0]

# -------------------------------
# 2. PROPORTIONAL LIMIT
# -------------------------------
linear_stress = np.polyval(coeffs, strain)
error = np.abs(stress - linear_stress)

threshold = 0.02 * max(stress)
prop_index = np.argmax(error > threshold)
sigma_prop = stress[prop_index]

# -------------------------------
# 3. YIELD STRESS
# -------------------------------
offset = 0.002
offset_line = E * (strain - offset)

diff = stress - offset_line
yield_index = np.where(diff > 0)[0][0]
sigma_yield = stress[yield_index]

# -------------------------------
# 4. MAX STRESS
# -------------------------------
max_index = np.argmax(stress)
sigma_max = stress[max_index]

# -------------------------------
# 5. COMPRESSIVE VALUES
# -------------------------------
epsilon_c = strain[max_index]

# ΔL from actuator (IMPORTANT)
delta_L = L0 - length[max_index]

# Force at max load
force_max = force[max_index]

# -------------------------------
# PRINT RESULTS
# -------------------------------
print("\n===== RESULTS =====")
print(f"Young's Modulus (E): {sci_notation(E)} Pa")
print(f"Proportional Limit: {sci_notation(sigma_prop)} Pa")
print(f"Yield Stress: {sci_notation(sigma_yield)} Pa")
print(f"Maximum Stress: {sci_notation(sigma_max)} Pa")

print("\n===== COMPRESSIVE VALUES =====")
print(f"Compressive Stress: {sci_notation(sigma_max)} Pa")
print(f"Compressive Strain: {epsilon_c:.4f}")
print(f"Change in Length (ΔL): {delta_L:.6f} mm")
print(f"Force at Max Load: {force_max:.2f} N")

# -------------------------------
# PLOT
# -------------------------------
plt.figure(figsize=(12,8))

plt.plot(strain, stress, linewidth=3, label='Stress-Strain Curve')
plt.plot(strain, linear_stress, '--', linewidth=2, label='Linear Fit')
plt.plot(strain, offset_line, '--', linewidth=2, label='0.2% Offset')

plt.scatter(strain[prop_index], sigma_prop, s=100, label='Proportional Limit')
plt.scatter(strain[yield_index], sigma_yield, s=100, label='Yield Point')
plt.scatter(epsilon_c, sigma_max, s=120, label='Max Stress (UTS)')

plt.xlabel('Strain (mm/mm)', fontsize=14)
plt.ylabel('Stress (Pa)', fontsize=14)
plt.title('Stress-Strain Curve (Compressive Test)', fontsize=16)

plt.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()